[project]
name = 'Self-Experimentation-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.biohacking-data]
path = 'contracts/biohacking-data.clar'
clarity_version = 2
epoch = 2.5

[contracts.experiment-protoco]
path = 'contracts/experiment-protoco.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
